rawdata <- read.table("household_power_consumption.txt", sep = ";", header = T, na.strings = "?")
rawdata <- rawdata[as.Date(rawdata[,1], "%d/%m/%Y") == as.Date('2007-02-01') | as.Date(rawdata[,1], "%d/%m/%Y") == as.Date('2007-02-02'),]
par(mfrow = c(2,2))
par(mar = c(5,5,1,1))
plot(rawdata$Time, rawdata$Global_active_power, lwd = 0.001, xaxt = "n", ylab = "Global active power")
axis(1,c(0, 720, 1440), c("Thu", "Fri", "Sat"))
plot(rawdata$Time, rawdata$Voltage, lwd = 0.001, xaxt = "n", ylab = "Voltage", xlab = "Date time")
axis(1,c(0, 720, 1440), c("Thu", "Fri", "Sat"))
plot(rawdata$Time, rawdata$Sub_metering_1, lwd = 0.001, xaxt = "n", ylab = "Energy sub metering")
axis(1,c(0, 720, 1440), c("Thu", "Fri", "Sat"))
lines(rawdata$Sub_metering_2, lty = 1, col = "red")
lines(rawdata$Sub_metering_3, lty = 1, col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1, col = c("black", "red", "blue"), bty = "n")
plot(rawdata$Time, rawdata$Global_reactive_power, lwd = 0.001, xaxt = "n", ylab = "Global reactive power", xlab = "Date time")
axis(1,c(0, 720, 1440), c("Thu", "Fri", "Sat"))